plots:
  eda:
    class_balance: "class_balance_breast_cancer"
    feature_means_std: "feature_means_std_breast_cancer"
    correlation_heatmap: "correlation_heatmap_breast_cancer"

directories:
  docs: "docs/"
  pdf_figures: "docs/figures_as_pdf/"
  png_figures: "docs/figures_as_png/"

  data: "data/"
  src: "src/"
  notebooks: "notebooks/"
  config: "config/"
  
  models: "models/"

values:
  RANDOM_SEED: 42
  FEATURE_SHIFT: "mean radius"

  hospital_a_export: "hospital_a.csv"
  hospital_b_export: "hospital_b.csv"
  test_set_export: "test_set.csv"

