model:
  layers:
    - type: Linear
      in_features: 30
      out_features: 64
    - type: ReLU
    - type: Dropout
      p: 0.3
    - type: Linear
      in_features: 64
      out_features: 32
    - type: ReLU
    - type: Dropout
      p: 0.2
    - type: Linear
      in_features: 32
      out_features: 1
