server:
  address: "localhost:8080"
  num_rounds: 20

model:
  type: "BreastCancerMLP"
  layers:
    - type: Linear
      in_features: 30
      out_features: 64
    - type: ReLU
    - type: Dropout
      p: 0.3
    - type: Linear
      in_features: 64
      out_features: 32
    - type: ReLU
    - type: Dropout
      p: 0.2
    - type: Linear
      in_features: 32
      out_features: 1

strategy:
  fraction_fit: 1.0
  fraction_evaluate: 1.0
  min_fit_clients: 2
  min_evaluate_clients: 2
  min_available_clients: 2
  evaluate_fn: null
